# Generated by Django 3.0.6 on 2020-05-14 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plataformas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=30)),
                ('fabricante', models.CharField(max_length=30)),
                ('tipo', models.CharField(choices=[('c', 'consola'), ('p', 'pc'), ('m', 'movil')], max_length=1)),
                ('generacion', models.CharField(max_length=30)),
                ('capacidad_disco', models.CharField(max_length=30)),
                ('gpu', models.CharField(max_length=30)),
                ('soporte', models.CharField(max_length=30)),
                ('web_oficial', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='VideoJuego',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('genero', models.CharField(choices=[('a', 'accion'), ('d', 'deportes'), ('e', 'estrategia')], max_length=1)),
                ('fabricante', models.CharField(max_length=30)),
                ('clasificacion', models.CharField(choices=[('n', 'E10+(niño)'), ('a', 'T(Adolecente)'), ('m', 'M+17(Maduro)'), ('a', 'A0+18(Adulto)')], max_length=1)),
                ('ano_lanzamiento', models.DateField()),
                ('max_jugadores', models.IntegerField()),
                ('jugabilidad', models.CharField(choices=[('1', 'Primera Persona'), ('3', 'Tercera Persona')], max_length=1)),
                ('web_oficial', models.URLField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='myFolder/')),
                ('trailer', models.URLField()),
                ('ranking', models.DecimalField(decimal_places=1, max_digits=1)),
                ('plataformas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='videojuego.Plataformas')),
            ],
        ),
    ]
