# Generated by Django 3.0.6 on 2020-05-17 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videojuego', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videojuego',
            name='imagen',
            field=models.FileField(blank=True, null=True, upload_to='myFolder/'),
        ),
    ]
