# Generated by Django 3.0.6 on 2020-05-17 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videojuego', '0002_auto_20200517_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videojuego',
            name='plataformas',
        ),
        migrations.AddField(
            model_name='videojuego',
            name='plataformas',
            field=models.ManyToManyField(to='videojuego.Plataformas'),
        ),
        migrations.AlterField(
            model_name='videojuego',
            name='ranking',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
