# Generated by Django 3.0.6 on 2020-05-21 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videojuego', '0003_auto_20200517_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videojuego',
            name='nombre',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
