# Generated by Django 3.0.6 on 2020-05-24 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videojuego', '0004_auto_20200521_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videojuego',
            name='genero',
            field=models.CharField(choices=[('a', 'accion'), ('d', 'deportes'), ('e', 'estrategia'), ('c', 'carreras')], max_length=1),
        ),
        migrations.AlterField(
            model_name='videojuego',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
