# Generated by Django 3.0.6 on 2020-05-25 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videojuego', '0005_auto_20200524_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videojuego',
            name='fabricante',
            field=models.CharField(max_length=100),
        ),
    ]
