# Generated by Django 3.0.6 on 2020-05-30 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videojuego', '0006_auto_20200525_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videojuego',
            name='nombre',
            field=models.CharField(help_text='Ya existe el nombre del videojuego', max_length=100, unique=True),
        ),
    ]
